/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CommonUtil: typeof import('wot-design-uni').CommonUtil
  const EffectScope: typeof import('vue').EffectScope
  const Storage: typeof import('../utils/storage').Storage
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const adjustColorBrightness: typeof import('../utils/color').adjustColorBrightness
  const auth: typeof import('../api/auth').default
  const checkLogin: typeof import('../utils/auth').checkLogin
  const clearAll: typeof import('../utils/auth').clearAll
  const clearTokens: typeof import('../utils/auth').clearTokens
  const clearUserInfo: typeof import('../utils/auth').clearUserInfo
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const createRouter: typeof import('uni-mini-router').createRouter
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('../utils/index').debounce
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getAccessToken: typeof import('../utils/auth').getAccessToken
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getRefreshToken: typeof import('../utils/auth').getRefreshToken
  const getUserInfo: typeof import('../utils/auth').getUserInfo
  const h: typeof import('vue').h
  const hexToRgb: typeof import('../utils/color').hexToRgb
  const inject: typeof import('vue').inject
  const isLoggedIn: typeof import('../utils/auth').isLoggedIn
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onAddToFavorites: typeof import('@dcloudio/uni-app').onAddToFavorites
  const onBackPress: typeof import('@dcloudio/uni-app').onBackPress
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onError: typeof import('@dcloudio/uni-app').onError
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onHide: typeof import('@dcloudio/uni-app').onHide
  const onLaunch: typeof import('@dcloudio/uni-app').onLaunch
  const onLoad: typeof import('@dcloudio/uni-app').onLoad
  const onMounted: typeof import('vue').onMounted
  const onNavigationBarButtonTap: typeof import('@dcloudio/uni-app').onNavigationBarButtonTap
  const onNavigationBarSearchInputChanged: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputChanged
  const onNavigationBarSearchInputClicked: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputClicked
  const onNavigationBarSearchInputConfirmed: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputConfirmed
  const onNavigationBarSearchInputFocusChanged: typeof import('@dcloudio/uni-app').onNavigationBarSearchInputFocusChanged
  const onPageNotFound: typeof import('@dcloudio/uni-app').onPageNotFound
  const onPageScroll: typeof import('@dcloudio/uni-app').onPageScroll
  const onPullDownRefresh: typeof import('@dcloudio/uni-app').onPullDownRefresh
  const onReachBottom: typeof import('@dcloudio/uni-app').onReachBottom
  const onReady: typeof import('@dcloudio/uni-app').onReady
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onResize: typeof import('@dcloudio/uni-app').onResize
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onShareAppMessage: typeof import('@dcloudio/uni-app').onShareAppMessage
  const onShareTimeline: typeof import('@dcloudio/uni-app').onShareTimeline
  const onShow: typeof import('@dcloudio/uni-app').onShow
  const onTabItemTap: typeof import('@dcloudio/uni-app').onTabItemTap
  const onThemeChange: typeof import('@dcloudio/uni-app').onThemeChange
  const onUnhandledRejection: typeof import('@dcloudio/uni-app').onUnhandledRejection
  const onUnload: typeof import('@dcloudio/uni-app').onUnload
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const requireLogin: typeof import('../utils/auth').requireLogin
  const resolveComponent: typeof import('vue').resolveComponent
  const rgbToHex: typeof import('../utils/color').rgbToHex
  const setAccessToken: typeof import('../utils/auth').setAccessToken
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setRefreshToken: typeof import('../utils/auth').setRefreshToken
  const setUserInfo: typeof import('../utils/auth').setUserInfo
  const setupStore: typeof import('../store/index').setupStore
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const store: typeof import('../store/index').store
  const storeToRefs: typeof import('pinia').storeToRefs
  const toLoginPage: typeof import('../utils/toLoginPage').toLoginPage
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useMessage: typeof import('wot-design-uni').useMessage
  const useModel: typeof import('vue').useModel
  const useNavigationBar: typeof import('../composables/useNavigationBar').useNavigationBar
  const useNotify: typeof import('wot-design-uni').useNotify
  const useRoute: typeof import('uni-mini-router').useRoute
  const useRouter: typeof import('uni-mini-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useStomp: typeof import('../composables/useStomp').useStomp
  const useTabbar: typeof import('../composables/useTabbar').useTabbar
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeStore: typeof import('../store/modules/theme.store').useThemeStore
  const useToast: typeof import('wot-design-uni').useToast
  const useUserStore: typeof import('../store/modules/user.store').useUserStore
  const user: typeof import('../api/user').default
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ThemeColorOption, ThemeMode, RequiredThemeVars } from '../store/modules/theme.store'
  import('../store/modules/theme.store')
  // @ts-ignore
  export type { LoginFormData, RefreshToekenBody, LoginResult, CaptchaInfo, LogoutBody } from '../api/auth'
  import('../api/auth')
  // @ts-ignore
  export type { ForgetPasswordForm, RegisterForm, UserPageQuery, searchSelectDataType, UserForm, UserInfo, MenuTable, deptTreeType, roleSelectorType, positionSelectorType, UserProfileForm, PasswordChangeForm, ResetPasswordForm } from '../api/user'
  import('../api/user')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly CommonUtil: UnwrapRef<typeof import('wot-design-uni')['CommonUtil']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Storage: UnwrapRef<typeof import('../utils/storage')['Storage']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly adjustColorBrightness: UnwrapRef<typeof import('../utils/color')['adjustColorBrightness']>
    readonly auth: UnwrapRef<typeof import('../api/auth')['default']>
    readonly checkLogin: UnwrapRef<typeof import('../utils/auth')['checkLogin']>
    readonly clearAll: UnwrapRef<typeof import('../utils/auth')['clearAll']>
    readonly clearTokens: UnwrapRef<typeof import('../utils/auth')['clearTokens']>
    readonly clearUserInfo: UnwrapRef<typeof import('../utils/auth')['clearUserInfo']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createRouter: UnwrapRef<typeof import('uni-mini-router')['createRouter']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('../utils/index')['debounce']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getAccessToken: UnwrapRef<typeof import('../utils/auth')['getAccessToken']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getRefreshToken: UnwrapRef<typeof import('../utils/auth')['getRefreshToken']>
    readonly getUserInfo: UnwrapRef<typeof import('../utils/auth')['getUserInfo']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hexToRgb: UnwrapRef<typeof import('../utils/color')['hexToRgb']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isLoggedIn: UnwrapRef<typeof import('../utils/auth')['isLoggedIn']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onAddToFavorites: UnwrapRef<typeof import('@dcloudio/uni-app')['onAddToFavorites']>
    readonly onBackPress: UnwrapRef<typeof import('@dcloudio/uni-app')['onBackPress']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onError: UnwrapRef<typeof import('@dcloudio/uni-app')['onError']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onHide: UnwrapRef<typeof import('@dcloudio/uni-app')['onHide']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onLoad: UnwrapRef<typeof import('@dcloudio/uni-app')['onLoad']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNavigationBarButtonTap: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarButtonTap']>
    readonly onNavigationBarSearchInputChanged: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputChanged']>
    readonly onNavigationBarSearchInputClicked: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputClicked']>
    readonly onNavigationBarSearchInputConfirmed: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputConfirmed']>
    readonly onNavigationBarSearchInputFocusChanged: UnwrapRef<typeof import('@dcloudio/uni-app')['onNavigationBarSearchInputFocusChanged']>
    readonly onPageNotFound: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageNotFound']>
    readonly onPageScroll: UnwrapRef<typeof import('@dcloudio/uni-app')['onPageScroll']>
    readonly onPullDownRefresh: UnwrapRef<typeof import('@dcloudio/uni-app')['onPullDownRefresh']>
    readonly onReachBottom: UnwrapRef<typeof import('@dcloudio/uni-app')['onReachBottom']>
    readonly onReady: UnwrapRef<typeof import('@dcloudio/uni-app')['onReady']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onResize: UnwrapRef<typeof import('@dcloudio/uni-app')['onResize']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onShareAppMessage: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareAppMessage']>
    readonly onShareTimeline: UnwrapRef<typeof import('@dcloudio/uni-app')['onShareTimeline']>
    readonly onShow: UnwrapRef<typeof import('@dcloudio/uni-app')['onShow']>
    readonly onTabItemTap: UnwrapRef<typeof import('@dcloudio/uni-app')['onTabItemTap']>
    readonly onThemeChange: UnwrapRef<typeof import('@dcloudio/uni-app')['onThemeChange']>
    readonly onUnhandledRejection: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnhandledRejection']>
    readonly onUnload: UnwrapRef<typeof import('@dcloudio/uni-app')['onUnload']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly requireLogin: UnwrapRef<typeof import('../utils/auth')['requireLogin']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly rgbToHex: UnwrapRef<typeof import('../utils/color')['rgbToHex']>
    readonly setAccessToken: UnwrapRef<typeof import('../utils/auth')['setAccessToken']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setRefreshToken: UnwrapRef<typeof import('../utils/auth')['setRefreshToken']>
    readonly setUserInfo: UnwrapRef<typeof import('../utils/auth')['setUserInfo']>
    readonly setupStore: UnwrapRef<typeof import('../store/index')['setupStore']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly store: UnwrapRef<typeof import('../store/index')['store']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toLoginPage: UnwrapRef<typeof import('../utils/toLoginPage')['toLoginPage']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useMessage: UnwrapRef<typeof import('wot-design-uni')['useMessage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNavigationBar: UnwrapRef<typeof import('../composables/useNavigationBar')['useNavigationBar']>
    readonly useNotify: UnwrapRef<typeof import('wot-design-uni')['useNotify']>
    readonly useRoute: UnwrapRef<typeof import('uni-mini-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('uni-mini-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTabbar: UnwrapRef<typeof import('../composables/useTabbar')['useTabbar']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemeStore: UnwrapRef<typeof import('../store/modules/theme.store')['useThemeStore']>
    readonly useToast: UnwrapRef<typeof import('wot-design-uni')['useToast']>
    readonly useUserStore: UnwrapRef<typeof import('../store/modules/user.store')['useUserStore']>
    readonly user: UnwrapRef<typeof import('../api/user')['default']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}