export const addressOptions = [
  { label: "北京市", value: "北京市", children: [{ label: "北京市", value: "北京市" }] },
  { label: "上海市", value: "上海市", children: [{ label: "上海市", value: "上海市" }] },
  { label: "天津市", value: "天津市", children: [{ label: "天津市", value: "天津市" }] },
  { label: "重庆市", value: "重庆市", children: [{ label: "重庆市", value: "重庆市" }] },
  { label: "河北省", value: "河北省", children: ["石家庄市", "唐山市", "秦皇岛市", "邯郸市", "保定市", "张家口市"].map((city) => ({ label: city, value: city })) },
  { label: "山西省", value: "山西省", children: ["太原市", "大同市", "阳泉市", "长治市", "晋城市", "临汾市"].map((city) => ({ label: city, value: city })) },
  { label: "辽宁省", value: "辽宁省", children: ["沈阳市", "大连市", "鞍山市", "抚顺市", "锦州市"].map((city) => ({ label: city, value: city })) },
  { label: "吉林省", value: "吉林省", children: ["长春市", "吉林市", "四平市", "通化市"].map((city) => ({ label: city, value: city })) },
  { label: "黑龙江省", value: "黑龙江省", children: ["哈尔滨市", "齐齐哈尔市", "牡丹江市", "大庆市"].map((city) => ({ label: city, value: city })) },
  { label: "江苏省", value: "江苏省", children: ["南京市", "无锡市", "徐州市", "常州市", "苏州市", "南通市"].map((city) => ({ label: city, value: city })) },
  { label: "浙江省", value: "浙江省", children: ["杭州市", "宁波市", "温州市", "嘉兴市", "湖州市", "绍兴市"].map((city) => ({ label: city, value: city })) },
  { label: "安徽省", value: "安徽省", children: ["合肥市", "芜湖市", "蚌埠市", "淮南市", "安庆市"].map((city) => ({ label: city, value: city })) },
  { label: "福建省", value: "福建省", children: ["福州市", "厦门市", "泉州市", "漳州市", "莆田市"].map((city) => ({ label: city, value: city })) },
  { label: "江西省", value: "江西省", children: ["南昌市", "九江市", "赣州市", "宜春市", "上饶市"].map((city) => ({ label: city, value: city })) },
  { label: "山东省", value: "山东省", children: ["济南市", "青岛市", "淄博市", "烟台市", "潍坊市", "临沂市"].map((city) => ({ label: city, value: city })) },
  { label: "河南省", value: "河南省", children: ["郑州市", "洛阳市", "开封市", "新乡市", "南阳市"].map((city) => ({ label: city, value: city })) },
  { label: "湖北省", value: "湖北省", children: ["武汉市", "黄石市", "襄阳市", "宜昌市", "荆州市"].map((city) => ({ label: city, value: city })) },
  { label: "湖南省", value: "湖南省", children: ["长沙市", "株洲市", "湘潭市", "衡阳市", "岳阳市"].map((city) => ({ label: city, value: city })) },
  { label: "广东省", value: "广东省", children: ["广州市", "深圳市", "珠海市", "佛山市", "东莞市", "中山市"].map((city) => ({ label: city, value: city })) },
  { label: "海南省", value: "海南省", children: ["海口市", "三亚市", "儋州市"].map((city) => ({ label: city, value: city })) },
  { label: "四川省", value: "四川省", children: ["成都市", "绵阳市", "德阳市", "南充市", "宜宾市"].map((city) => ({ label: city, value: city })) },
  { label: "贵州省", value: "贵州省", children: ["贵阳市", "遵义市", "六盘水市", "安顺市"].map((city) => ({ label: city, value: city })) },
  { label: "云南省", value: "云南省", children: ["昆明市", "曲靖市", "玉溪市", "大理市"].map((city) => ({ label: city, value: city })) },
  { label: "陕西省", value: "陕西省", children: ["西安市", "咸阳市", "宝鸡市", "渭南市"].map((city) => ({ label: city, value: city })) },
  { label: "甘肃省", value: "甘肃省", children: ["兰州市", "天水市", "酒泉市", "庆阳市"].map((city) => ({ label: city, value: city })) },
  { label: "内蒙古自治区", value: "内蒙古自治区", children: ["呼和浩特市", "包头市", "赤峰市", "鄂尔多斯市"].map((city) => ({ label: city, value: city })) },
  { label: "广西壮族自治区", value: "广西壮族自治区", children: ["南宁市", "柳州市", "桂林市", "北海市"].map((city) => ({ label: city, value: city })) },
  { label: "宁夏回族自治区", value: "宁夏回族自治区", children: ["银川市", "石嘴山市", "吴忠市"].map((city) => ({ label: city, value: city })) },
  { label: "新疆维吾尔自治区", value: "新疆维吾尔自治区", children: ["乌鲁木齐市", "克拉玛依市", "喀什市"].map((city) => ({ label: city, value: city })) },
  { label: "西藏自治区", value: "西藏自治区", children: ["拉萨市", "日喀则市", "林芝市"].map((city) => ({ label: city, value: city })) },
  { label: "青海省", value: "青海省", children: ["西宁市", "海东市"].map((city) => ({ label: city, value: city })) },
  { label: "香港特别行政区", value: "香港特别行政区", children: [{ label: "香港特别行政区", value: "香港特别行政区" }] },
  { label: "澳门特别行政区", value: "澳门特别行政区", children: [{ label: "澳门特别行政区", value: "澳门特别行政区" }] },
  { label: "台湾省", value: "台湾省", children: ["台北市", "高雄市", "台中市", "台南市"].map((city) => ({ label: city, value: city })) },
];
