/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/login/index" |
  "/pages/mine/index" |
  "/pages/work/index" |
  "/subPages/about/index" |
  "/subPages/account/index" |
  "/subPages/asyncEcharts/index" |
  "/subPages/ci/index" |
  "/subPages/create-uni/index" |
  "/subPages/echarts/index" |
  "/subPages/feedback/index" |
  "/subPages/icon/index" |
  "/subPages/pinia/index" |
  "/subPages/profile/index" |
  "/subPages/request/index" |
  "/subPages/router/demo-aftereach" |
  "/subPages/router/demo-guard" |
  "/subPages/router/demo-object" |
  "/subPages/router/demo-params" |
  "/subPages/router/demo-protected" |
  "/subPages/router/demo-query" |
  "/subPages/router/demo-string" |
  "/subPages/router/index" |
  "/subPages/settings/index" |
  "/subPages/skills/index" |
  "/subPages/styles/index" |
  "/subPages/uni-ku-root/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/work/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
